# Generated by Django 5.0.6 on 2024-06-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='imagen',
            field=models.ImageField(upload_to='PC'),
        ),
        migrations.AlterField(
            model_name='software',
            name='imagen',
            field=models.ImageField(null=True, upload_to='software'),
        ),
    ]
