# Generated by Django 5.0.6 on 2024-07-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Item de Carrito', 'verbose_name_plural': 'Items de Carrito'},
        ),
    ]
