# Generated by Django 5.0.6 on 2024-07-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_itemcarrito_options'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto_tipo',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pc',
            name='visible_al_usuario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='software',
            name='visible_al_usuario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='imagen',
            field=models.ImageField(null=True, upload_to='PC'),
        ),
    ]
